spring:
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/install.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true